# <font color=blue>**TAREA  6** 

## <font color=blue>**- Ejercicio 1**
    
Investigar y ejemplificar diferencias entre np.array y np.matrix

np.matrix -> Permite la creacion de matrices en base a arrays o strings, siendo el tipo de objeto numpy.matrix, los np.matrix son una subclase de np.array por lo que pueden ser un poco mas lentos que estos (no significativo)

In [3]:
import numpy as np

In [11]:
EjemploMatrix = np.matrix('7 10 3; 105 9 77')
print(EjemploMatrix)
print(type(EjemploMatrix))

[[  7  10   3]
 [105   9  77]]
<class 'numpy.matrix'>


In [6]:
EjemploMatrix2 = np.matrix([[9,10, 25], [56,8, 4]])
print(EjemploMatrix2)

[[ 9 10 25]
 [56  8  4]]


np.matrix -> Permite la creacion de vectores de distintos tamaños, siende el tipo de objeto numpy.array

In [14]:
EjemploArray = np.array([[9,10, 25], [56,8, 4]])
print(EjemploArray)
print(type(EjemploArray))

[[ 9 10 25]
 [56  8  4]]
<class 'numpy.ndarray'>


## <font color=blue>**- Ejercicio 2**

**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicación de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producirá una nueva matriz con el mismo número de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la función "sigmoid"(descrita a continuación) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamaño pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la función sigmoid. El resultado debe ser un tensor con el mismo número de filas que la matriz X y una sola columna(una predicción para cada fila de X.

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [16]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1   
    return 1/(1+np.exp(-x))

In [17]:
H1_W = np.array([[0.25,-8],[0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],[1,2]])

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  

print(OL)

[[0.99995577]
 [0.99999332]]


## <font color=blue>**- Ejercicio 3**


Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Una vez tenemos la implementacion correcta, cambiar la funcion de activacion de la capa de salida por la funcion de activacion ReLu(https://en.wikipedia.org/wiki/Rectifier_(neural_networks)):

<img src="https://cdn-images-1.medium.com/max/1600/1*DfMRHwxY1gyyDmrIAd-gjQ.png">

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):